source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxCamera_Example' do
    platform :ios, '8.0'
    pod 'RxCamera', :path => '../'
  target 'RxCamera_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
